### PR TITLE
Roll back uncommitable transactions

### LINKED ISSUE #366: Commit failure unhandled, database left in unusable state
When sqlite is used from multiple processes at the same time, `COMMIT` may fail with "database is locked" error.

After that happens, all subsequent transactions in rusqlite fail with "cannot start a transaction within a transaction".

I think this is because:

```rust
    fn commit_(&mut self) -> Result<()> {
        self.committed = true;
        self.conn.execute_batch("COMMIT")
    }
```

Sets `self.committed = true;` without checking whether commit has succeeded, and when `COMMIT` fails, the transaction remains open — forever.

It should probably be: 

```rust
    fn commit_(&mut self) -> Result<()> {        
        self.conn.execute_batch("COMMIT")?;
        self.committed = true;
        Ok(())
    }
```

### PR DESCRIPTION
**Pull request by kornelski**
This fixes #366 for me

### CODE REVIEW

File: src/transaction.rs [hunk 1]
```diff
@@ -195,7 +197,7 @@ impl<'conn> Transaction<'conn> {
             return Ok(());
         }
         match self.drop_behavior() {
-            DropBehavior::Commit => self.commit_(),
+            DropBehavior::Commit => self.commit_().or_else(|_| self.rollback_()),
```
Comment (gwenn) [inline src/transaction.rs]: I am not sure but the `.or_else(|_| self.rollback_())` should only be done in `drop` (in case the user wants to wait and retry for example after `finish`).
And maybe the `rollback_` should only be called for some specific error code(s).

File: src/transaction.rs [hunk 2]
```diff
@@ -307,7 +310,7 @@ impl<'conn> Savepoint<'conn> {
             return Ok(());
         }
         match self.drop_behavior() {
-            DropBehavior::Commit => self.commit_(),
+            DropBehavior::Commit => self.commit_().or_else(|_| self.rollback()),
```
Comment (gwenn) [inline src/transaction.rs]: Above comment applies also here.

File: src/transaction.rs (hunk 1 above)
Comment (kornelski) [reply src/transaction.rs]: It's not possible to retry if `finish()` fails, because it consumes `self` and drops it.

Comment (gwenn) [reply src/transaction.rs]: Right, sorry.

**Comment by kornelski** [comment]
Added

**Comment by gwenn** [comment]
Thanks.
